# syntax = edrevo/dockerfile-plus

INCLUDE+ ./common/Dockerfile.base

# Needed to build for mingw, see
# http://lists.gnu.org/archive/html/info-gnu/2011-02/msg00020.html
ARG NCURSES_TARGET_OPTS="--enable-term-driver --enable-sp-funcs"

ARG TARGET_HOST="i686-w64-mingw32"
ARG MINGW_TOOLCHAIN="g++-mingw-w64-i686"
ARG WIN_PLATFORM="win32"

RUN apt update && apt install -y --force-yes \
    $MINGW_TOOLCHAIN \
    && rm -rf /var/lib/apt/lists/*

INCLUDE+ ./common/Dockerfile.gdb-deps
INCLUDE+ ./common/Dockerfile.win-python
INCLUDE+ ./common/Dockerfile.rust
