# syntax = edrevo/dockerfile-plus

ARG DOCKER_REGISTRY
ARG TOOLCHAIN_TAG

FROM ${DOCKER_REGISTRY}/esp32-toolchain-arm-cross:${TOOLCHAIN_TAG}

ARG TARGET_HOSTS="aarch64-linux-gnu"
ARG OPENSSL_BUILD_PLATFORM="linux-generic64"
ARG OPENSSL_TARGET_PLATFORM="linux-aarch64"
ARG TARGET_HOST="aarch64-linux-gnu"

INCLUDE+ ./common/Dockerfile.update-apt-sources

RUN set -ex;                                            \
    apt-get update                                      \
  && apt-get install -y -q --no-install-recommends      \
        libc6-dev                                       \
        linux-libc-dev                                  \
        libffi-dev:arm64                                \
  && rm -rf /var/lib/apt/lists/*

INCLUDE+ ./common/Dockerfile.gdb-deps
INCLUDE+ ./common/Dockerfile.python-builder
