.build_image: &build_image
  stage: images
  image: espressif/dind:1
  tags: [ "dind", "internet", "amd64" ]
  rules:
    - if: $BUILD_IMAGES
    - changes:
      - .gitlab/docker/**/*
  variables:
    QEMU_IMAGE: qemu-v5.2:2-20230522
    DOCKERFILE_NAME: Dockerfile.linux
    EXTRA_BUILD_ARGS: ""
    TARGET_HOST: ""
    OPENSSL_BUILD_PLATFORM: ""
    OPENSSL_TARGET_PLATFORM: ""
    RUST_TARGET_TRIPLET: ""
  artifacts:
    expire_in: 1 week
    when: on_failure
    paths:
      - ${CI_PROJECT_DIR}/build.log
  script:
    - cd .gitlab/docker
    # This is workaround for https://github.com/edrevo/dockerfile-plus/issues/13
    # After the bug is fixed, please remove the line below.
    - ./dockerfile-plus_workaround.sh ${DOCKERFILE_NAME} && cat ${DOCKERFILE_NAME}
    - echo -n $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - echo -n $DOCKER_REGISTRY_PASS | docker login -u $DOCKER_REGISTRY_USER --password-stdin $CI_DOCKER_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE/$IMAGE_NAME:latest || true
    - docker build
        --cache-from $CI_REGISTRY_IMAGE/$IMAGE_NAME:latest
        --file $DOCKERFILE_NAME
        --build-arg TARGET_HOST="$TARGET_HOST"
        --build-arg OPENSSL_BUILD_PLATFORM="$OPENSSL_BUILD_PLATFORM"
        --build-arg OPENSSL_TARGET_PLATFORM="$OPENSSL_TARGET_PLATFORM"
        --build-arg RUST_TARGET_TRIPLET="$RUST_TARGET_TRIPLET"
        ${EXTRA_BUILD_ARGS}
        --tag $CI_REGISTRY_IMAGE/$IMAGE_NAME:$CI_COMMIT_SHA
        --tag $CI_REGISTRY_IMAGE/$IMAGE_NAME:latest .
        > ${CI_PROJECT_DIR}/build.log
    - docker push $CI_REGISTRY_IMAGE/$IMAGE_NAME:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE/$IMAGE_NAME:latest


image_linux_x86:
  variables:
    IMAGE_NAME: gdb-build-linux-x86
    TARGET_HOST: "i586-linux-gnu"
    OPENSSL_BUILD_PLATFORM: "linux-generic64"
    OPENSSL_TARGET_PLATFORM: "linux-generic32"
    RUST_TARGET_TRIPLET: "i586-unknown-linux-gnu"
  extends: .build_image

image_linux_x86_64:
  variables:
    IMAGE_NAME: gdb-build-linux-x86_64
    TARGET_HOST: "x86_64-linux-gnu"
    OPENSSL_BUILD_PLATFORM: "linux-generic64"
    OPENSSL_TARGET_PLATFORM: "linux-generic64"
    RUST_TARGET_TRIPLET: "x86_64-unknown-linux-gnu"
  extends: .build_image

image_linux_armel:
  variables:
    IMAGE_NAME: gdb-build-linux-armel
    TARGET_HOST: "arm-linux-gnueabi"
    OPENSSL_BUILD_PLATFORM: "linux-generic64"
    OPENSSL_TARGET_PLATFORM: "linux-armv4"
    RUST_TARGET_TRIPLET: "arm-unknown-linux-gnueabi"
  extends: .build_image

image_linux_armhf:
  variables:
    IMAGE_NAME: gdb-build-linux-armhf
    TARGET_HOST: "arm-linux-gnueabihf"
    OPENSSL_BUILD_PLATFORM: "linux-generic64"
    OPENSSL_TARGET_PLATFORM: "linux-armv4"
    RUST_TARGET_TRIPLET: "arm-unknown-linux-gnueabihf"
  extends: .build_image

image_linux_arm64:
  variables:
    IMAGE_NAME: gdb-build-linux-arm64
    TARGET_HOST: "aarch64-linux-gnu"
    OPENSSL_BUILD_PLATFORM: "linux-generic64"
    OPENSSL_TARGET_PLATFORM: "linux-aarch64"
    RUST_TARGET_TRIPLET: "aarch64-unknown-linux-gnu"
  extends: .build_image

image_win_x86:
  variables:
    DOCKERFILE_NAME: Dockerfile.win
    IMAGE_NAME: gdb-build-win-x86
    TARGET_HOST: "i686-w64-mingw32"
    EXTRA_BUILD_ARGS: "--build-arg WIN_PLATFORM=win32 --build-arg MINGW_TOOLCHAIN=g++-mingw-w64-i686"
    RUST_TARGET_TRIPLET: "i686-pc-windows-gnu"
  extends: .build_image

image_win_x86_64:
  variables:
    DOCKERFILE_NAME: Dockerfile.win
    IMAGE_NAME: gdb-build-win-x86_64
    TARGET_HOST: "x86_64-w64-mingw32"
    EXTRA_BUILD_ARGS: "--build-arg WIN_PLATFORM=amd64 --build-arg MINGW_TOOLCHAIN=g++-mingw-w64-x86-64"
    RUST_TARGET_TRIPLET: "x86_64-pc-windows-gnu"
  extends: .build_image

image_macos_x86_64:
  variables:
    DOCKERFILE_NAME: Dockerfile.macos
    IMAGE_NAME: gdb-build-macos-x86_64
    TARGET_HOST: "x86_64-apple-darwin21.1"
    RUST_TARGET_TRIPLET: "x86_64-apple-darwin"
  extends: .build_image

image_macos_arm64:
  variables:
    DOCKERFILE_NAME: Dockerfile.macos
    IMAGE_NAME: gdb-build-macos-arm64
    TARGET_HOST: "aarch64-apple-darwin21.1"
    RUST_TARGET_TRIPLET: "aarch64-apple-darwin"
  extends: .build_image

image_dejagnu:
  variables:
    DOCKERFILE_NAME: Dockerfile.dejagnu
    IMAGE_NAME: gdb-test-dejagnu
    EXTRA_BUILD_ARGS: "--build-arg QEMU_IMAGE=$QEMU_IMAGE"
  extends: .build_image
