.*x-thead-ext-fail.s: Assembler messages:
.*x-thead-ext-fail.s:1: Error: improper immediate value \(32\)
.*x-thead-ext-fail.s:2: Error: improper immediate value \(33\)
.*x-thead-ext-fail.s:3: Error: improper immediate value \(32\)
.*x-thead-ext-fail.s:4: Error: illegal operands `ext a0,a1,31,31,10'
.*x-thead-ext-fail.s:5: Error: illegal operands `ext a0,a1,31'
.*x-thead-ext-fail.s:6: Error: illegal operands `ext a0,31'
.*x-thead-ext-fail.s:7: Error: improper immediate value \(32\)
.*x-thead-ext-fail.s:8: Error: improper immediate value \(33\)
.*x-thead-ext-fail.s:9: Error: improper immediate value \(32\)
.*x-thead-ext-fail.s:10: Error: illegal operands `extu a0,a1,31,31,10'
.*x-thead-ext-fail.s:11: Error: illegal operands `extu a0,a1,31'
.*x-thead-ext-fail.s:12: Error: illegal operands `extu a0,31'
