ARG GMP_VERSION=6.2.1
ARG MPFR_VERSION=4.2.2
ARG MPC_VERSION=1.2.0
ARG EXPAT_VERSION=2.4.1
ARG NCURSES_VERSION=6.5
ARG NCURSES_SHA256=136d91bc269a9a5785e5f9e980bc76ab57428f604ce3e5a5a90cebc767971cc6
ARG NCURSES_TARGET_OPTS

RUN wget --no-verbose --no-check-certificate https://gmplib.org/download/gmp/gmp-$GMP_VERSION.tar.lz && \
    tar --lzip -xvf gmp-$GMP_VERSION.tar.lz && \
    rm gmp-$GMP_VERSION.tar.lz && \
    cd gmp-$GMP_VERSION && \
    ./configure --enable-static --disable-shared --prefix=/opt/gmp-$TARGET_HOST --host=$TARGET_HOST && \
    make && make install
#will be removed after mpfr build

RUN wget --no-verbose --no-check-certificate https://www.mpfr.org/mpfr-current/mpfr-$MPFR_VERSION.tar.gz && \
    tar xzf mpfr-$MPFR_VERSION.tar.gz && \
    cd mpfr-$MPFR_VERSION && \
    ./configure --enable-static --disable-shared --with-gmp-build=$PWD/../gmp-$GMP_VERSION --prefix=/opt/mpfr-$TARGET_HOST --host=$TARGET_HOST && \
    make && make install && \
    cd .. && rm -fr mpfr-$MPFR_VERSION* gmp-$GMP_VERSION*

RUN wget --no-verbose --no-check-certificate https://www.multiprecision.org/downloads/mpc-$MPC_VERSION.tar.gz && \
    tar xzf mpc-$MPC_VERSION.tar.gz && \
    cd mpc-$MPC_VERSION && \
    export CFLAGS="-I/opt/gmp-$TARGET_HOST/include -I/opt/mpfr-$TARGET_HOST/include" && \
    export LDFLAGS="-L/opt/gmp-$TARGET_HOST/lib -L/opt/mpfr-$TARGET_HOST/lib" && \
    ./configure --enable-static --disable-shared --prefix=/opt/mpc-$TARGET_HOST --host=$TARGET_HOST && \
    make && make install && \
    cd .. && rm -fr mpc-$MPC_VERSION*

RUN curl -LO https://github.com/libexpat/libexpat/releases/download/R_${EXPAT_VERSION//./_}/expat-$EXPAT_VERSION.tar.gz && \
    tar xzf expat-$EXPAT_VERSION.tar.gz && \
    cd expat-$EXPAT_VERSION && \
    ./configure --enable-static --disable-shared --prefix=/opt/expat-$TARGET_HOST --host=$TARGET_HOST && \
    make && make install && \
    cd .. && rm -fr expat-$EXPAT_VERSION*

RUN wget --no-verbose https://ftp.gnu.org/pub/gnu/ncurses/ncurses-$NCURSES_VERSION.tar.gz && \
    echo "$NCURSES_SHA256 *ncurses-$NCURSES_VERSION.tar.gz" | sha256sum --check --strict - && \
    tar xzf ncurses-$NCURSES_VERSION.tar.gz && \
    pushd ncurses-$NCURSES_VERSION && \
    mkdir utils && \
    pushd utils && \
    $PWD/../configure && \
    make -C include && make -C progs tic infocmp && \
    export PATH=$PWD/progs:$PATH && \
    popd && \
    NCURSES_OPTS="--prefix=/opt/ncurses-$TARGET_HOST --host=$TARGET_HOST \
        --without-progs --without-debug --enable-termcap --enable-symlinks --without-manpages \
        --without-tests --without-cxx --without-cxx-binding --without-ada \
        --disable-database --disable-db-install --with-abi-version=5 \
        --with-fallbacks=linux,xterm,xterm-color,xterm-256color,vt100,ansi $NCURSES_TARGET_OPTS" && \
    ./configure $NCURSES_OPTS && \
    make -j$(nproc) && make install && \
    ./configure $NCURSES_OPTS --enable-widec && \
    make -j$(nproc) && make install && \
    popd && rm -fr ncurses-$NCURSES_VERSION*
