ARG RUST_TARGET_TRIPLET="please set target"
ARG RUST_VERSION=1.94.0

RUN  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh  -s -- -y --default-toolchain ${RUST_VERSION} \
 && . "$HOME/.cargo/env" \
 && rustup target add $RUST_TARGET_TRIPLET

ENV RUST_TARGET_TRIPLET=$RUST_TARGET_TRIPLET
ENV PATH="/root/.cargo/bin:$PATH"
